"""Citation validation: extract and verify [chunk_id] references in LLM answers.

All functions are pure — no classes, no shared state.
"""

import re
from typing import Any

# Matches any UUID (8-4-4-4-12 hex groups) enclosed in square brackets.
# chunk_ids are generated by uuid.uuid4() which produces lowercase hex, but
# the LLM may capitalise them, so the pattern is case-insensitive.
_CITATION_RE = re.compile(
    r"\[([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}"
    r"-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})\]"
)


def extract_citations(answer: str) -> list[str]:
    """
    Extract all UUID chunk_id citations from an LLM answer string.

    Citations are expected in the format ``[chunk_id]`` where ``chunk_id`` is
    a UUID (any version).  The same chunk_id may appear multiple times if the
    model cites it for several claims; duplicates are preserved in the output
    to reflect actual citation behaviour.

    Args:
        answer: Raw LLM response text.

    Returns:
        Ordered list of cited chunk_id strings (may contain duplicates).
    """
    return _CITATION_RE.findall(answer)


def validate_citations(
    answer: str,
    retrieved_chunks: list[dict[str, Any]],
) -> dict[str, Any]:
    """
    Check that every citation in *answer* refers to a chunk in *retrieved_chunks*.

    Duplicate citations are de-duplicated before classification so that a
    chunk_id cited three times counts once in ``valid`` or ``invalid``.

    Args:
        answer: Raw LLM response text.
        retrieved_chunks: The chunks passed to the LLM as context.  Each dict
                          must contain a ``chunk_id`` key.

    Returns:
        Dict with four keys:

        - ``valid`` — cited chunk_ids that exist in the retrieved set.
        - ``invalid`` — cited chunk_ids that do **not** exist in the retrieved
          set (hallucinated references).
        - ``uncited_chunks`` — chunk_ids in the retrieved set that were never
          cited in the answer (sorted for determinism).
        - ``all_valid`` — ``True`` iff ``invalid`` is empty.
    """
    raw_cited = extract_citations(answer)
    # Deduplicate while preserving first-occurrence order.
    cited_unique: list[str] = list(dict.fromkeys(raw_cited))

    retrieved_ids: set[str] = {chunk["chunk_id"] for chunk in retrieved_chunks}

    valid: list[str] = [cid for cid in cited_unique if cid in retrieved_ids]
    invalid: list[str] = [cid for cid in cited_unique if cid not in retrieved_ids]
    uncited_chunks: list[str] = sorted(retrieved_ids - set(cited_unique))

    return {
        "valid": valid,
        "invalid": invalid,
        "uncited_chunks": uncited_chunks,
        "all_valid": len(invalid) == 0,
    }
